<?php
/*мфссив объектов
    'title' - заголовок объявления (string)
    'name' - имя элемента которое используется при отправке формы (string)
    'important' - важное или нет  (bool)
    'dataTitle' - текст всплывающей подсказки (string)
    'hasDepend' - указывает на то, имеет ли элемент какие то зависимые элементы (bool)
    'optionValues' - массив объектов выпадающего списка (array)
        '0' - заголовок, который виден в списке
        '1' - значение элемента списка
        '2' - зависимости вкл. массив чисел (id элемента в списке, который должен отображаться при выборе данного элемента списка) (string)
        '3' - зависимости выкл. массив чисел (id элемента в списке, который должен скрыться при выборе данного элемента списка) (string)
    'showIfDependent' - если false - элемент будет отображаться только после того, как его зависимый родитель был выбран (bool)
    'inputSmall' - если тру - поле ввода наполовину меньше (bool)
    ''
    ''
    ''
    ''
 *
 *
 * добавить зависимости
 * добавить скрипт для всплывающих подсказок
 * */
$elementsArray = [
    [
        'id' => 0,
        'title' => 'Название',
        'name' => 'title',
        'important' => true,
    ],
    [
        'id' => 9,
        'title' => 'Состояние',
        'name' => 'condition',
        'optionValues' => [['Новое',1],['Б/у',2]],
        'important' => true,
        'inputSmall'=> true
    ],
    [
        'id' => 1,
        'title' => 'Тип',
        'name' => 'type',
        'hasDepend' => true,
        'optionValues' => [['Шины',1,'3,6,7,8','2,4,5'],['Диски',2,'2,4,5','3,6,7,8'],['Проставки',3,'1','2,3,4,5,6,7,8'],['Прочее',4,'1','2,3,4,5,6,7,8']],
        'important' => true,
        'inputSmall'=> true
    ],
    [
        'id' => 2,
        'title' => 'Диаметр диска',
        'name' => 'diameter',
        'optionValues' => [12,13,14,15,16,17,18,19,20,21,22,23],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'inputSmall'=> true,
        'showIfDependent' => true
    ],
    [
        'id' => 3,
        'title' => 'Диаметр шины',
        'name' => 'diameter',
        'optionValues' => [12,13,14,15,16,17,18,19,20,21,22,23],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'showIfDependent' => true
    ],
    [
        'id' => 4,
        'title' => 'Количество отверстий',
        'name' => 'holesCount',
        'optionValues' => [3,4,5,6,7,8,9,10],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'showIfDependent' => true
    ],
    [
        'id' => 5,
        'title' => 'Диаметр по центрам отверстий',
        'name' => 'holesDia',
        'optionValues' => [98,100,105,112,114,120],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'showIfDependent' => true
    ],
    [
        'id' => 6,
        'title' => 'Ширина шины(мм)',
        'name' => 'tireWidth',
        'optionValues' => [155,165,175,185,195,205,215,225,235,245,255,265,275,285,295,305],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'showIfDependent' => true
    ],
    [
        'id' => 7,
        'title' => 'Высота профиля(%)',
        'name' => 'tireHeight',
        'optionValues' => [30,35,40,45,50,55,60,65,70,75,80],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'showIfDependent' => true
    ],
    [
        'id' => 8,
        'title' => 'Тип шины',
        'name' => 'tireType',
        'optionValues' => [['Лето',1],['Зима',2],['Демисезон',3]],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'showIfDependent' => true
    ],
    [
        'id' => 10,
        'title' => '',
        'name' => ''
    ],
    [
        'id' => 0,
        'title' => '',
        'name' => ''
    ],
    [
        'id' => 0,
        'title' => '',
        'name' => ''
    ],
    [
        'id' => 0,
        'title' => '',
        'name' => ''
    ],
    [
        'id' => 0,
        'title' => '',
        'name' => ''
    ],
    [
        'id' => 0,
        'title' => '',
        'name' => ''
    ],
    [
        'id' => 0,
        'title' => '',
        'name' => ''
    ]
];
$dependArray = [];
?>

<div class="main_slider_wrap">
    <div class="container">
        <div class="row">
            <div class="content">
                <div class="ttl">Продать у нас свои шины, диски, проставки или что-либо ещё - легко!</div>
                <?php foreach ($elementsArray as $elementKey => $element):?>
                    <?php if(empty($element['title']) OR empty($element['name'])) continue;?>

                    <div id="el<?=$element['id'];?>" class="line<?php if(!empty($element['showIfDependent'])) echo' hide';?>" <?php if(!empty($dependArray[$elementKey])) echo' depend'?> data-name="<?= $element['name'];?>">
                        <div class="inline_trate"><?php if(!empty($element['important']) AND $element['important']) echo'<i class="important">*</i>';?><?= $element['title'] ?></div>
                        <div class="inline_midelt <?php if(!empty($element['inputSmall'])) echo'smaller';?> <?php if(!empty($element['dataTitle'])) echo' question"><i class="question" data-title="'.$element['dataTitle'].'">?</i>'; else echo'">';?>
                        <?php if(!empty($element['optionValues'])): ?>
                            <select class="element_<?=$elementKey;?>"<?php if(!empty($element['hasDepend'])) echo' onchange="depending('.$elementKey.');"';?>><option disabled selected></option>
                                <?php foreach ($element['optionValues'] as $type): ?>
                                    <?php if(is_array($type)): ?>
                                        <option <?php if(!empty($type[2]) and !empty($type[3])) echo'dependOn="'.$type[2].'" dependOff="'.$type[3].'" ';?>value="<?=$type[1];?>"><?=$type[0];?></option>
                                    <?php else: ?>
                                        <option value="<?=$type;?>"><?=$type;?></option>
                                    <?php endif;?>
                                <?php endforeach;?>
                            </select></div>
                        <?php else: ?>
                            <input type="text"></div>
                        <?php endif;?>
                        <div class="inline_holder"><span class="error"><i class="fa fa-angle-left "></i></span></div>
                    </div>
                <?php endforeach;?>
                <div class="postprend">
                    <div class="info_place">
                        Блок с некой информацией
                    </div>
                    <div class="btn_place">
                        <button type="submit">отправить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function depending(id)
    {
        var element = $('select.element_'+id+' option:selected');
        var dependOff = stringToArray(element.attr('dependOff'));
        var dependOn = stringToArray(element.attr('dependOn'));
        dependOff.forEach(function(el)
        {
            $('#el'+el).addClass('hide');
        });
        dependOn.forEach(function(el)
        {
            $('#el'+el).removeClass('hide');
        });
    }
    function stringToArray(string)
    {
        var array = [];
        string.split(',').forEach(function(el){array.push(parseInt(el))})
        return array;
    }
</script>
<style>
/* START   page for adding ad*/
    .main_slider_wrap .container .row .ttl { border-bottom: 1px solid #e2e2e2; font-weight: 700; padding-bottom: 10px; margin-bottom: 10px;}
    .main_slider_wrap .container .row .line {}
    .main_slider_wrap .container .row .line.hide {display: none;}
    .main_slider_wrap .container .row .line>div { display: inline-block; padding: 13px 5px;}

    .main_slider_wrap .container .row .line .inline_trate { width: 270px; font-weight: 700; text-align: right; font-size: smaller;}
    .main_slider_wrap .container .row .line .inline_trate i.important { color: #c30000; margin-right: 5px; font-size: 13pt; }

    .main_slider_wrap .container .row .line .inline_midelt { width: 500px; height: auto; position:relative; text-align: left; background: #fff; border-left: 2px solid #dddcdc; padding: 0; }
    .main_slider_wrap .container .row .line .inline_midelt input,
    .main_slider_wrap .container .row .line .inline_midelt select { width: 100%; height: 26px; padding-left: 5px; background: #fff; border: none; border: 2px solid #dddcdc; border-left: none; }
    .main_slider_wrap .container .row .line .inline_midelt input:focus,
    .main_slider_wrap .container .row .line .inline_midelt select:focus { outline: none; }
    .main_slider_wrap .container .row .line .inline_midelt i.question { position: absolute; left: 5px; top: 2px;color: #005564; cursor: pointer;}
    .main_slider_wrap .container .row .line .inline_midelt.smaller input,
    .main_slider_wrap .container .row .line .inline_midelt.smaller select { width: 30%; }
    .main_slider_wrap .container .row .line .inline_midelt.question input,
    .main_slider_wrap .container .row .line .inline_midelt.question select { padding-left: 18px; }

    .main_slider_wrap .container .row .line .inline_holder {  }
    .main_slider_wrap .container .row .line .inline_holder span.error { display: none; color: #c30000; font-size: 11pt; }
    .main_slider_wrap .container .row .line .inline_holder span.error i { color: #000; margin-right: 5px; font-size: 13pt;}

    .main_slider_wrap .container .row .postprend { border-top: 1px solid #e2e2e2; padding: 10px 0px; }
    .main_slider_wrap .container .row .postprend>div { display: inline-block;}
    .main_slider_wrap .container .row .postprend .info_place {  width: 500px; font-size: 11px; }
    .main_slider_wrap .container .row .postprend .btn_place { width: 270px; text-align: right; vertical-align: top;}
/* END   page for adding ad*/
@media (max-width: 1000px) {
    .main_slider_wrap .container .row .ttl { font-size: smaller; }
    .main_slider_wrap .container .row .line .inline_trate { width: 30%; }
    .main_slider_wrap .container .row .line .inline_midelt { width: 65%;  }
    .main_slider_wrap .container .row .line .inline_holder {  display: none; }


}

</style>