<?php

$dependArray = [
    'condition' => [
        'title' => 'Состояние',
        'name' => 'condition',
        'options' => [
            'new' => 'Новое',
            'used' => 'Б/У'
        ]
    ],
    'type' => [
        'title' => 'Тип',
        'name' => 'type',
        'options' => [
            1 => 'Диски',
            2 => 'Шины',
            3 => 'Проставки',
            4 => 'Прочее'
        ]
    ],
    'wheel-1' => [
        'title' => 'Диаметр диска',
        'name' => 'disk1',
        'options' => [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    ],
    'wheel-2' => [
        'title' => 'Кол-во отверстий',
        'name' => 'disk2',
        'options' => [3, 4, 5, 6, 7, 8, 9, 10]
    ],
    'wheel-3' => [
        'title' => 'Диаметр по центрам отверстий',
        'name' => 'disk3',
        'options' => [98, 100, 105, 112, 114, 120]
    ],
    'wheel-4' => [
        'title' => 'Производитель',
        'name' => '',
        'options' => [
            1 => 'A',
            2 => 'B',
            3 => 'C'
        ]

    ],
    'wheel-5' => [
        'title' => 'Модель',
        'name' => '',
        'options' => [
            1 => 'A1'
        ]
        /* chain too wheel-4 */
    ],
    'tires-1' => [
        'title' => 'Диаметр шины',
        'name' => 'tires1',
        'options' => [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    ],
    'tires-2' => [
        'title' => 'Ширина шины(мм)',
        'name' => 'tires2',
        'options' => [155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255, 265, 275, 285, 295, 305]
    ],
    'tires-3' => [
        'title' => 'Высота профиля(%)',
        'name' => 'tires3',
        'options' => [30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]
    ],
    'tires-4' => [
        'title' => 'Тип шины',
        'name' => 'tires4',
        'options' => [
            1 => 'Лето',
            2 => 'Зима',
            3 => 'Демисезон'
        ]
    ],


];
?>

<div class="main_slider_wrap">
    <div class="container">
        <div class="row">
            <div class="content">
                <form id="form_add_advert" class="form-horizontal" role="form" action="" target="_self" method="post">
                    <fieldset>
                        <div class="full-width-in-thin col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <legend>Продать у нас свои шины, диски, проставки или что-либо ещё - легко!</legend>
                        </div>
                        <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="select"
                                       class="col-lg-4 col-md-4 control-label"><?= $dependArray['type']['title']; ?>
                                    :</label>
                                <div class="col-lg-8 col-md-8">
                                    <select name="<?= $dependArray['type']['name']; ?>" class="form-control">
                                        <?php foreach ($dependArray['type']['options'] as $key => $value) : ?>
                                            <option value="<?= $key; ?>"><?= $value; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label for="select"
                                       class="col-lg-4 col-md-4 control-label"><?= $dependArray['condition']['title']; ?>
                                    :</label>
                                <div class="col-lg-8 col-md-8">
                                    <select name="<?= $dependArray['condition']['name']; ?>" class="form-control">
                                        <?php foreach ($dependArray['condition']['options'] as $key => $value) : ?>
                                            <option value="<?= $key; ?>"><?= $value; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="advert-type-1">
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['wheel-4']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['wheel-4']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['wheel-4']['options'] as $key => $value) : ?>
                                                <option value="<?= $key; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['wheel-5']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['wheel-5']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['wheel-5']['options'] as $key => $value) : ?>
                                                <option value="<?= $key; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['wheel-1']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['wheel-1']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['wheel-1']['options'] as $key => $value) : ?>
                                                <option value="<?= $value; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['wheel-2']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['wheel-2']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['wheel-2']['options'] as $key => $value) : ?>
                                                <option value="<?= $value; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['wheel-3']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['wheel-3']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['wheel-3']['options'] as $key => $value) : ?>
                                                <option value="<?= $value; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="advert-type-2" style="display: none;">
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['tires-1']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['tires-1']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['tires-1']['options'] as $key => $value) : ?>
                                                <option value="<?= $value; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['tires-2']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['tires-2']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['tires-2']['options'] as $key => $value) : ?>
                                                <option value="<?= $value; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['tires-3']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['tires-3']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['tires-3']['options'] as $key => $value) : ?>
                                                <option value="<?= $value; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="full-width-in-thin col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group">
                                    <label for="select"
                                           class="col-lg-4 col-md-4 control-label"><?= $dependArray['tires-4']['title']; ?>
                                        :</label>
                                    <div class="col-lg-8 col-md-8">
                                        <select name="<?= $dependArray['tires-4']['name']; ?>" class="form-control">
                                            <?php foreach ($dependArray['tires-4']['options'] as $key => $value) : ?>
                                                <option value="<?= $key; ?>"><?= $value; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </fieldset>
                    <fieldset>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                            <button id="add-advert" type="button" class="btn btn-orange btn-lg">Подать</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>