<?php
/*мфссив объектов
    'title' заголовок объявления (string)
    'name' - имя элемента которое используется при отправке формы (string)
    'important' важное или нет  (bool)
    'dataTitle' - текст всплывающей подсказки (string)
    'optionValues' - массив объектов выпадающего списка (array)
        '0' - заголовок, который виден в списке
        '1' - значение элемента списка
        '2' - зависимости. массив чисел (id элемента в списке, который должен отображаться при выборе данного элемента списка) (array)
    'showIfDependent' - если false - элемент будет отображаться только после того, как его зависимый родитель был выбран (bool)
    'inputSmall' - если тру - поле ввода наполовину меньше (bool)
    ''
    ''
    ''
    ''
 *
 *
 * добавить зависимости
 * добавить скрипт для всплывающих подсказок
 * */
$elementsArray = [
    [
        'title' => 'Название',
        'important' => true,
        'inputSmall'=> false
    ],
    [
        'title' => 'Тип',
        'name' => 'type',
        'optionValues' => [['Шины',1,[3]],['Диски',2,[2]],['Проставки',3,[]],['Прочее',4,[]]],
        'important' => true,
        'inputSmall'=> true
    ],
    [
        'title' => 'Диаметр диска',
        'name' => 'diameter',
        'optionValues' => [12,13,14,15,16,17,18,19,20,21,22,23],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'optionValues' => [
            ['Шины',1],
            ['Диски',2],
            ['Проставки',3],
            ['Прочее',4]
        ],
        'inputSmall'=> true
    ],
    [
        'title' => 'Диаметр шины',
        'name' => 'diameter',
        'optionValues' => [12,13,14,15,16,17,18,19,20,21,22,23],
        'important' => false,
        'inputSmall'=> true,
        'dataTitle' => 'Some to write',
        'showIfDependent' => true
    ],
    [
        'title' => '',
        'name' => ''
    ],
    [
        'title' => '',
        'name' => ''
    ],
    [
        'title' => '',
        'name' => ''
    ],
    [
        'title' => '',
        'name' => ''
    ]
];

?>

<div class="main_slider_wrap">
    <div class="container">
        <div class="row">
            <div class="content">
                <div class="ttl">Продать у нас свои шины, диски, проставки или что-либо ещё - легко!</div>
                <?php foreach ($elementsArray as $element):?>
                <?php if(empty($element['title']) OR empty($element['name'])) continue;?>
                <div class="line<?php if(isset($element['showIfDependent']) AND !$element['showIfDependent']) echo' hide';?>" data-name="<?= $element['name'];?>">
                    <div class="inline_trate"><?php if(empty($element['important']) OR  !$element['important']) echo'<i class="important">*</i>';?><?= $element['title'] ?></div>
                    <div class="inline_midelt <?php if($element['inputSmall']) echo'smaller';?><?php if(!empty($element['dataTitle'])) echo' question"><i class="question" data-title="'.$element['dataTitle'].'">?</i>'; else echo'">';?>
                    <?php
                        if(!empty($element['optionValues']))
                        {
                            echo'<select><option disabled selected></option>';
                            foreach ($element['optionValues'] as $type){
                                if(is_array($type))
                                    echo'<option value="'.$type[1].'">'.$type[0].'</option>';
                                else
                                    echo'<option value="'.$type.'">'.$type.'</option>';
                            }
                            echo'</select>';
                        } else
                            echo '<input type="text">';?></div>
                    <div class="inline_holder"><span class="error"><i class="fa fa-angle-left "></i></span></div>
                </div>
                <?php endforeach;?>
                <div class="postprend">
                    <div class="info_place">
                        Блок с некой информацией
                    </div>
                    <div class="btn_place">
                        <button type="submit">отправить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
/* START   page for adding ad*/
    .main_slider_wrap .container .row .ttl { border-bottom: 1px solid #e2e2e2; font-weight: 700; padding-bottom: 10px; margin-bottom: 10px;}
    .main_slider_wrap .container .row .line {}
    .main_slider_wrap .container .row .line.hide {display: none;}
    .main_slider_wrap .container .row .line>div { display: inline-block; padding: 13px 5px;}

    .main_slider_wrap .container .row .line .inline_trate { width: 270px; font-weight: 700; text-align: right; font-size: smaller;}
    .main_slider_wrap .container .row .line .inline_trate i.important { color: #c30000; margin-right: 5px; font-size: 13pt; }

    .main_slider_wrap .container .row .line .inline_midelt { width: 500px; height: auto; position:relative; text-align: left; background: #fff; border-left: 2px solid #dddcdc; padding: 0; }
    .main_slider_wrap .container .row .line .inline_midelt input,
    .main_slider_wrap .container .row .line .inline_midelt select { width: 100%; height: 26px; padding-left: 5px; background: #fff; border: none; border: 2px solid #dddcdc; border-left: none; }
    .main_slider_wrap .container .row .line .inline_midelt input:focus,
    .main_slider_wrap .container .row .line .inline_midelt select:focus { outline: none; }
    .main_slider_wrap .container .row .line .inline_midelt i.question { position: absolute; left: 5px; top: 2px;color: #005564; cursor: pointer;}
    .main_slider_wrap .container .row .line .inline_midelt.smaller input,
    .main_slider_wrap .container .row .line .inline_midelt.smaller select { width: 30%; }
    .main_slider_wrap .container .row .line .inline_midelt.question input,
    .main_slider_wrap .container .row .line .inline_midelt.question select { padding-left: 18px; }

    .main_slider_wrap .container .row .line .inline_holder {  }
    .main_slider_wrap .container .row .line .inline_holder span.error { display: none; color: #c30000; font-size: 11pt; }
    .main_slider_wrap .container .row .line .inline_holder span.error i { color: #000; margin-right: 5px; font-size: 13pt;}

    .main_slider_wrap .container .row .postprend { border-top: 1px solid #e2e2e2; padding: 10px 0px; }
    .main_slider_wrap .container .row .postprend>div { display: inline-block;}
    .main_slider_wrap .container .row .postprend .info_place {  width: 500px; font-size: 11px; }
    .main_slider_wrap .container .row .postprend .btn_place { width: 270px; text-align: right; vertical-align: top;}
/* END   page for adding ad*/


</style>