<!-- SLIDER -->
<div class="main_slider_wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12 text-center">
                <div class="inline text-right">
                    <div class="m_logo h1 no-margin">
                        carick.com
                    </div>
                    <div class="m_slogan text-uppercase">
                        Главное в деталях
                    </div>
                </div>
                <div class="form-group"></div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8 col-xxs-10 col-xxs-push-1 col-xs-push-2 col-sm-push-3 col-md-push-3 col-lg-push-4">
                <div class="m_srch">
                    <div id="imaginary_container">
                        <div class="input-group stylish-input-group">
                            <input type="text" class="form-control"  placeholder="Поиск" >
                            <span class="input-group-addon">
                                <button type="submit">
                                    <span class="fa fa-search"></span>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- SLIDER END-->
<!-- GALLERY BLOCK -->
<div class="gallery_wrap panel-body">
    <div class="container">
        <div class="row">
            <!-- auto start-->
            <div class="col-lg-2 col-md-3 col-sm-4 main-makes hidden-xs">
                <?php
                echo $this->partial('index/mainPageTemplates/verticalLogos.phtml', [
                    'makes' => $this->makes,
                    'screenSize' => 'lg',
                    'h1' => 'Авто',
                ]);
                ?>
            </div>
            <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                <?php echo $this->partial('index/mainPageTemplates/verticalLogos.phtml', [
                    'makes' => $this->makes,
                    'screenSize' => 'xs',
                    'h1' => 'Авто',
                ]);
                ?>
            </div>
            <!-- auto end-->
            <!-- disk start -->
            <div class="col-lg-2 col-md-3 col-sm-4 main-makes hidden-xs">
                <?php echo $this->partial('index/mainPageTemplates/verticalLogos.phtml', [
                    'makes' => $this->makes,
                    'screenSize' => 'lg',
                    'h1' => 'Бренды',
                ]);
                ?>
            </div>
            <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                <?php echo $this->partial('index/mainPageTemplates/verticalLogos.phtml', [
                    'makes' => $this->makes,
                    'screenSize' => 'xs',
                    'h1' => 'Бренды',
                ]);
                ?>
            </div>
            <!-- disk end -->
            <!-- horizontal blocks start-->
            <div class="col-lg-8 col-md-6 col-sm-4 hidden-xs">
                <div class="row">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12"><h1>Шины</h1></div>
                    </div>
                    <?php
                        $dataSizeArray = [
                            'lg' => [
                                'visible-lg','hidden-sm hidden-md'
                            ],
                            'md' => [
                                'visible-md','hidden-sm hidden-lg'
                            ],
                            'sm' => [
                                'visible-sm','hidden-md hidden-lg'
                            ],
                        ];

                        foreach ($dataSizeArray as $screenSize => $className) : ?>
                            <div class="<?= $className[0]; ?> hidden-xs <?= $className[1]; ?>">
                                <?php echo $this->partial('index/mainPageTemplates/horizontalLogos.phtml', [
                                    'makes' => $this->makes,
                                    'screenSize' => $screenSize,
                                ]);
                                ?>
                            </div>
                        <?php endforeach;
                    ?>
                </div>
                <div class="row">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12"><h1>Диски</h1></div>
                    </div>
                    <?php
                        foreach ($dataSizeArray as $screenSize => $className) : ?>
                        <div class="<?= $className[0]; ?> hidden-xs <?= $className[1]; ?>">
                            <?php echo $this->partial('index/mainPageTemplates/horizontalLogos.phtml', [
                                'makes' => $this->makes,
                                'screenSize' => $screenSize,
                            ]);
                            ?>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="row">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12"><h1>Проставки</h1></div>
                    </div>
                    <?php
                    foreach ($dataSizeArray as $screenSize => $className) : ?>
                        <div class="<?= $className[0]; ?> hidden-xs <?= $className[1]; ?>">
                            <?php echo $this->partial('index/mainPageTemplates/horizontalLogos.phtml', [
                                'makes' => $this->makes,
                                'screenSize' => $screenSize,
                            ]);
                            ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="visible-xs">
                <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                    <?php echo $this->partial('index/mainPageTemplates/verticalLogos.phtml', [
                        'makes' => $this->makes,
                        'screenSize' => 'xs',
                        'h1' => 'Шины',
                    ]);
                    ?>
                </div>
                <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                    <?php echo $this->partial('index/mainPageTemplates/verticalLogos.phtml', [
                        'makes' => $this->makes,
                        'screenSize' => 'xs',
                        'h1' => 'Диски',
                    ]);
                    ?>
                </div>
                <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                    <?php echo $this->partial('index/mainPageTemplates/verticalLogos.phtml', [
                        'makes' => $this->makes,
                        'screenSize' => 'xs',
                        'h1' => 'Проставки',
                    ]);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="panel panel-login no-margin-bottom">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-6">
                                <a href="#" class="active" id="login-form-link">Вход</a>
                            </div>
                            <div class="col-xs-6">
                                <a href="#" id="register-form-link">Регистрация</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form id="login-form" action="" method="post" role="form" style="display: block;">
                                    <div class="form-group">
                                        <input type="text" name="username" id="log-email" tabindex="1" class="form-control" placeholder="Email" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="log-password" tabindex="2" class="form-control" placeholder="Пароль">
                                    </div>
                                    <!--<div class="form-group text-center">
                                        <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                        <label for="remember"> Запомнить меня</label>
                                    </div>-->
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-orange" value="Войти">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="text-center">
                                                    <a href="javascript:void(0);" tabindex="5" id="forgot-password-link" class="forgot-password">Забыли пароль?</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div id="error-log-block"></div>
                                    </div>
                                </form>
                                <form id="register-form" action="" method="post" role="form" style="display: none;">
                                    <div class="form-group">
                                        <input type="text" name="username" id="reg-username" tabindex="1" class="form-control" placeholder="Имя пользователя" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="email" name="email" id="reg-email" tabindex="1" class="form-control" placeholder="Email" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" id="reg-password" tabindex="2" class="form-control" placeholder="Пароль">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="confirm-password" id="reg-confirm-password" tabindex="2" class="form-control" placeholder="Повторить пароль">
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-orange" value="Зарегистрироваться">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div id="error-reg-block"></div>
                                    </div>
                                </form>
                                <form id="forgot-form" action="" method="post" role="form" style="display: none;">
                                    <div class="form-group">
                                        <input type="email" name="email" id="fog-email" tabindex="1" class="form-control" placeholder="Email" value="">
                                    </div>
                                    <div class="form-group" style="display:none;">
                                        <input type="password" name="password" id="fog-password" tabindex="2" class="form-control" placeholder="Пароль">
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6 col-sm-offset-3">
                                                <input type="submit" name="forgot-submit" id="forgot-submit" tabindex="4" class="form-control btn btn-orange" value="Выслать пароль.">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div id="error-forget-block"></div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="Login">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">Уже существует</div>
        </div>
    </div>
</div>
<!-- GALLERY BLOCK END-->