<!-- SLIDER -->
<div class="main_slider_wrap">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12 text-center">
                <div class="inline text-right">
                    <div class="m_logo h1 no-margin">
                        carick.com
                    </div>
                    <div class="m_slogan text-uppercase">
                        Главное в деталях
                    </div>
                </div>
                <div class="form-group"></div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8 col-xxs-10 col-xxs-push-1 col-xs-push-2 col-sm-push-3 col-md-push-3 col-lg-push-4">
                <div class="m_srch">
                    <div id="imaginary_container">
                        <div class="input-group stylish-input-group">
                            <input type="text" class="form-control main_search_input"  placeholder="Поиск">
                            <span class="input-group-addon">
                                <button type="submit" class="subbmit-search-request">
                                    <span class="fa fa-search"></span>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="main_search_block">
    <div class="container">
        <?php echo $this->partial('index/mainpagetemplates/mainsearchinputblock.phtml'); ?>
    </div>
</div>
<!-- SLIDER END-->
<!-- GALLERY BLOCK -->
<div class="gallery_wrap panel-body" id="main_page_logos_div">
    <div class="container">
        <div class="row">
            <!-- auto start-->
            <div class="col-lg-4 col-md-4 col-sm-4">
                <div class="col-lg-6 col-md-6 col-sm-6 main-makes hidden-xs">
                    <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                        'makes' => $this->topTires,
                        'screenSize' => 'lg',
                        'maxSize' => 6,
                        'h1' => 'Шины',
                        'href' => '/tires'
                    ]);
                    ?>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 main-makes hidden-xs">
                    <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                        'makes' => $this->topWheels,
                        'screenSize' => 'lg',
                        'maxSize' => 6,
                        'h1' => 'Диски',
                        'href' => '/wheels'
                    ]);
                    ?>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                <div class="col-lg-12 col-md-12 col-sm-12 main-makes hidden-xs">
                    <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                        'makes' => $this->topAuto,
                        'topAutoJson' => $this->topAutoJson,
                        'urlImg' => "$this->siteUtl:$this->serverPort",
                        'screenSize' => 'lg',
                        'double' => 1,
                        'maxSize' => 13,
                        'h1' => 'Авто',
                        'href' => '/makes'
                    ]);
                    ?>
                </div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-4">
                <div class="col-lg-6 col-md-6 col-sm-6 main-makes hidden-xs">
                    <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                        'makes' => $this->topSpaces,
                        'screenSize' => 'lg',
                        'maxSize' => 6,
                        'h1' => 'Проставки',
                        'href' => '/spacers'
                    ]);
                    ?>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 main-makes hidden-xs">
                    <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                        'makes' => $this->topBrands,
                        'screenSize' => 'lg',
                        'maxSize' => 6,
                        'h1' => 'Бренды',
                        'href' => '/brands'
                    ]);
                    ?>
                </div>
            </div>
            <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                    'makes' => $this->topTires,
                    'screenSize' => 'xs',
                    'h1' => 'Шины',
                    'href' => '/tires'
                ]);
                ?>
            </div>
            <!-- auto end-->
            <!-- brend start -->

            <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                    'makes' => $this->topWheels,
                    'screenSize' => 'xs',
                    'h1' => 'Диски',
                    'href' => '/wheels'
                ]);
                ?>
            </div>
            <!-- brend end -->
            <!-- tires start -->

            <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                    'makes' => $this->topAuto,
                    'screenSize' => 'xs',
                    'h1' => 'Авто',
                    'href' => '/makes'
                ]);
                ?>
            </div>
            <!-- tires end -->
            <!-- disk start -->

            <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                    'makes' => $this->topSpaces,
                    'screenSize' => 'xs',
                    'h1' => 'Проставки',
                    'href' => '/spacers'
                ]);
                ?>
            </div>
            <!-- dist end -->
            <!-- sets start -->
            <div class="col-xs-12 col-xxs-12 main-makes visible-xs">
                <?php echo $this->partial('index/mainpagetemplates/verticallogos.phtml', [
                    'makes' => $this->topBrands,
                    'screenSize' => 'xs',
                    'h1' => 'Бренды',
                    'href' => '/brands'
                ]);
                ?>
            </div>
            <!-- sets end -->

        </div>
    </div>
</div>
<!-- SEARCH RESULTS BLOCK -->
<div class="search-main-ajax-results" style="display:none;">
    <div class="container">
        <div class="row">
            <div id="search-results">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="Login">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">Уже существует</div>
        </div>
    </div>
</div>
<!-- GALLERY BLOCK END-->