<div class="gallery_wrap panel-body" id="main_page_logos_div">
    <div class="container">
        <div class="row">
            <!-- auto start-->
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12 text-center bottom-line">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12 text-center bottom-line">
                            <h1><?= $this->title; ?></h1>
                        </div>
                                <?php foreach ($this->data as $value):?>
                                    <?php
                                    $x = ($value['img_position']*100);
                                    $background = "background-image: url('../public/images/avto_makes.png');";
                                    $background .= "background-size: cover;";
                                    $background .= "background-position: -" . $x . "px 0";
                                    ?>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12 text-center">
                                    <div class="logo_block inline" style="<?= $background; ?>">
                                        <a class="" href="#" title="<?= $value['title']; ?>"></a>
                                    </div>

                        </div>
                                <?php endforeach;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>