<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Carick.com</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="<?= $this->baseUrl; ?>/public/css/bootstrap.min.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?= $this->baseUrl; ?>/public/css/font-awesome.min.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?= $this->baseUrl; ?>/public/css/styles.css" type="text/css" media="screen, projection" />
        <link rel="stylesheet" href="<?= $this->baseUrl; ?>/public/css/addgrid.css" type="text/css" media="screen, projection" />
        <script src="<?= $this->baseUrl; ?>/public/js/jquery-2.1.4.min.js"></script>
        <script src="<?= $this->baseUrl; ?>/public/js/bootstrap.min.js"></script>
        <script src="<?= $this->baseUrl; ?>/public/js/script.js" type="text/javascript"></script>
    </head>
    <body>
        <div class="site_wrap">
            <!-- HEADER -->
            <header>
                <nav class="navbar navbar-default no-border-radius no-margin" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12 text-xs-center text-xxs-center">
                                    <div class="form-group"></div>
                                    <div class="inline">
                                        <div class="logo h2 no-margin"><a href="#">Carick.com</a></div>
                                        <div class="slogan text-right text-uppercase">Главное в деталях</div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center">
                                    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center"></div>
                                    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center">
                                            <div class="form-group main-logined-dropdawn"></div>
                                            <?php
                                                if ($this->autorizated) : ?>
                                                <div class="row main-logined-dropdawn">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center">
                                                        <button type="button" class="btn btn-orange btn-lg" data-toggle="" data-target="#">
                                                            <a class="button_link" href="<?= $this->serverUrl()?>/add ">Подать обьявление</a>
                                                        </button>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center">
                                                        <div class="dropdown margin-dropwown">
                                                            <button
                                                                class="btn btn-orange btn-lg dropdown-toggle"
                                                                type="button"
                                                                data-toggle="dropdown"
                                                            ><?= $this->userName['name']; ?></button>
                                                            <ul class="dropdown-menu">
                                                                 <li><a href="#">Объявления</a></li>
                                                                 <li><a href="#">Сообщения</a></li>
                                                                 <li><a href="#">Кабинет</a></li>
                                                                 <li><a href="#">Настройки</a></li>
                                                                 <li><a href="#" id="logout-user">Выйти</a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            <?php else : ?>
                                                 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center"></div>
                                                 <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center">
                                                    <button type="button" class="btn btn-orange btn-lg" data-toggle="modal" data-target="#loginModal">
                                                        Вход\Регистрация
                                                    </button>
                                                 </div>
                                            <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                    </div><!-- /.container-fluid -->
                </nav>
            </header>
            <!-- HEADER END-->
            <?= $this->layout()->content; ?>
            <!-- FOOTER -->
            <div class="footer_wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-6 col-xxs-12"></div>
                        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-6 col-xxs-12"></div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12">
                            <div class="bot_cont">
                                Carick.com. Все права защищены 2016.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- FOOTER END-->
        </div>
    </body>
</html>