<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Carick.com</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="<?= $this->baseUrl(); ?>/public/css/bootstrap.min.css" type="text/css"
              media="screen, projection"/>
        <link rel="stylesheet" href="<?= $this->baseUrl(); ?>/public/css/font-awesome.min.css" type="text/css"
              media="screen, projection"/>
        <link rel="stylesheet" href="<?= $this->baseUrl(); ?>/public/css/styles.css" type="text/css"
              media="screen, projection"/>
        <link rel="stylesheet" href="<?= $this->baseUrl(); ?>/public/css/addgrid.css" type="text/css"
              media="screen, projection"/>
        <script src="<?= $this->baseUrl(); ?>/public/js/jquery-2.1.4.min.js"></script>
        <script src="<?= $this->baseUrl(); ?>/public/js/bootstrap.min.js"></script>
        <script src="<?= $this->baseUrl(); ?>/public/js/script.js" type="text/javascript"></script>
        <script src="<?= $this->baseUrl(); ?>/public/js/imageUpload.js" type="text/javascript"></script>
    </head>
    <body id="dev">
        <div class="site_wrap">
            <!-- HEADER -->
            <header>
                <nav class="navbar navbar-default no-border-radius no-margin" role="navigation">
                    <div class="container">
                        <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12 text-xs-center text-xxs-center">
                                    <div class="form-group"></div>
                                    <div class="inline">
                                        <div class="logo h2 no-margin"><a href="<?= $this->baseUrl(); ?>">Carick.com</a></div>
                                        <div class="slogan text-right text-uppercase">Диски и шины Украины</div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12 text-right text-xs-center text-xxs-center">
                                            <div class="form-group"></div>
                                            <?php
                                                if ($this->autorizated) : ?>
                                                <div class="btn-group">
                                                    <button id="add-advert" type="button" class="btn btn-orange btn-lg">Подать обьявление</button>
                                                    <button type="button" class="btn btn-orange btn-lg dropdown-toggle no-padding" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <img class="main-menu-disk" src="<?= $this->baseUrl; ?>/public/images/disk_w.svg" alt="">
                                                    </button>
                                                    <ul class="dropdown-menu main-logined-dropdawn">
                                                        <li><a href="/user">Кабинет</a></li>
                                                        <li><a href="/user/adverts">Объявления</a></li>
                                                        <li><a href="/user/messages">Сообщения</a></li>
                                                        <li><a href="/user/settings">Настройки</a></li>
                                                        <li><a href="javascript:void(0);" class="logout-user">Выйти</a></li>
                                                    </ul>
                                                </div>
                                                <div class="form-group main-logined-dropdawn"></div>
                                                    <?php if ($this->userData->roleId == User::ROLE_ADMIN):?>
                                                        <a href="/ajax/configsoverwrite">обновить конфиги в бд</a>
                                                    <?php endif;?>
                                            <?php else : ?>
                                                <button type="button" class="btn btn-orange btn-lg" data-toggle="modal" data-target="#loginModal">
                                                    Вход\Регистрация
                                                </button>
                                                <div class="form-group main-logined-dropdawn"></div>
                                            <?php endif; ?>
                                </div>
                            </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                    </div><!-- /.container-fluid -->
                </nav>
            </header>
            <!-- Modal -->
            <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="Login">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            <div class="panel panel-login no-margin-bottom">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <a href="#" class="active" id="login-form-link">Вход</a>
                                        </div>
                                        <div class="col-xs-6">
                                            <a href="#" id="register-form-link">Регистрация</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <form id="login-form" action="" method="post" role="form" style="display: block;">
                                                <div class="form-group">
                                                    <input type="text" name="username" id="log-email" tabindex="1" class="form-control" placeholder="Email" value="">
                                                </div>
                                                <div class="form-group">
                                                    <input type="password" name="password" id="log-password" tabindex="2" class="form-control" placeholder="Пароль">
                                                </div>
                                                <!--<div class="form-group text-center">
                                                    <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                                    <label for="remember"> Запомнить меня</label>
                                                </div>-->
                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="col-sm-6 col-sm-offset-3">
                                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-orange" value="Войти">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="text-center">
                                                                <a href="javascript:void(0);" tabindex="5" id="forgot-password-link" class="forgot-password">Забыли пароль?</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div id="error-log-block"></div>
                                                </div>
                                            </form>
                                            <form id="register-form" action="" method="post" role="form" style="display: none;">
                                                <div class="form-group">
                                                    <input type="text" name="username" id="reg-username" tabindex="1" class="form-control" placeholder="Имя пользователя" value="">
                                                </div>
                                                <div class="form-group">
                                                    <input type="email" name="email" id="reg-email" tabindex="1" class="form-control" placeholder="Email" value="">
                                                </div>
                                                <div class="form-group">
                                                    <input type="password" name="password" id="reg-password" tabindex="2" class="form-control" placeholder="Пароль">
                                                </div>
                                                <div class="form-group">
                                                    <input type="password" name="confirm-password" id="reg-confirm-password" tabindex="2" class="form-control" placeholder="Повторить пароль">
                                                </div>
                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="col-sm-6 col-sm-offset-3">
                                                            <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-orange" value="Зарегистрироваться">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div id="error-reg-block"></div>
                                                </div>
                                            </form>
                                            <form id="forgot-form" action="" method="post" role="form" style="display: none;">
                                                <div class="form-group">
                                                    <input type="email" name="email" id="fog-email" tabindex="1" class="form-control" placeholder="Email" value="">
                                                </div>
                                                <div class="form-group" style="display:none;">
                                                    <input type="password" name="password" id="fog-password" tabindex="2" class="form-control" placeholder="Пароль">
                                                </div>
                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="col-sm-6 col-sm-offset-3">
                                                            <input type="submit" name="forgot-submit" id="forgot-submit" tabindex="4" class="form-control btn btn-orange" value="Выслать пароль.">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div id="error-forget-block"></div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal -->
            <!-- HEADER END-->
            <?= $this->layout()->content; ?>
            <!-- FOOTER -->
            <div class="footer_wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-6 col-xxs-12"></div>
                        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-6 col-xxs-12"></div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xxs-12">
                            <div class="bot_cont">
                                Carick.com. Все права защищены 2016.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- FOOTER END-->
        </div>
    </body>
</html>