<div class="main_search_block show-search">
    <div class="container">
        <?php echo $this->partial('index/mainpagetemplates/mainsearchinputblock.phtml'); ?>
    </div>
</div>
<div class="search-main-ajax-results">
    <div class="container">
        <div class="row">
            <div id="search-results">
                <div class="row">
                    <div class="search-results">
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 col-xxs-12" style="height: 200px;">
                            <img style="" class="advert-img" src="../../public/images/2.jpg" title="" alt="">
                        </div>
                        <div class="col-lg-9 col-md-8 col-sm-6 col-xs-12 col-xxs-12 search-result-h1"
                             style="height:30px;">
                            НАЗВАНИЕ
                        </div>
                        <div class="col-lg-9 col-md-8 col-sm-6 col-xs-12 col-xxs-12 search-result-body"
                             style="height:140px;">
                            ЧТОТО
                        </div>
                        <div class="col-lg-9 col-md-8 col-sm-6 col-xs-12 search-result-cost" style="height:30px;">
                            ЦЕНА
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="search-results">
                        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 col-xxs-12" style="height: 200px;">
                            <img style="" class="advert-img" src="../../public/images/2.jpg" title="" alt="">
                        </div>
                        <div class="col-lg-9 col-md-8 col-sm-6 col-xs-12 col-xxs-12 search-result-h1"
                             style="height:30px;">
                            НАЗВАНИЕ
                        </div>
                        <div class="col-lg-9 col-md-8 col-sm-6 col-xs-12 col-xxs-12 search-result-body"
                             style="height:140px;">
                            ЧТОТО
                        </div>
                        <div class="col-lg-9 col-md-8 col-sm-6 col-xs-12 search-result-cost" style="height:30px;">
                            ЦЕНА
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>