<?= $this->htmlMenu; ?>
<div class="main_slider_wrap">
    <div class="container full-desktop-height">
        <div class="row form-horizontal">
            <div class="form-group col-xs-12 col-xxs-12">
                <div class="col-sm-12 text-center">Контактные Данные</div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <label for="input-phone" class="col-sm-6 control-label">Контактный телефон</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="input-phone" placeholder="Контактный телефон" value="<?= $this->userData->contactPhone; ?>">
                </div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <label for="input-email" class="col-sm-6 control-label">Контактный email</label>
                <div class="col-sm-4">
                    <input type="email" class="form-control" id="input-email" placeholder="Контактный email" value="<?= $this->userData->contactEmail; ?>">
                </div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <label for="input-link-vk" class="col-sm-6 col-xs-12 control-label">Ссылка на профиль VK</label>
                <div class="col-sm-4 col-xs-12">
                    <input type="text" class="form-control" id="input-link-vk" placeholder="Ссылка на профиль VK" value="<?= $this->userData->contactLink1; ?>">
                </div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <label for="input-link-dr" class="col-sm-6 col-xs-12 control-label">Ссылка на профиль DRIVE</label>
                <div class="col-sm-4 col-xs-12">
                    <input type="text" class="form-control" id="input-link-dr" placeholder="Ссылка на профиль DRIVE" value="<?= $this->userData->contactLink2; ?>">
                </div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <div class="col-sm-offset-5 col-sm-9">
                    <button id="save-personal-data" type="button" class="btn btn-orange">Сохранить</button>
                </div>
            </div>
        </div>
    </div>
</div>

