<?= $this->htmlMenu; ?>
<div class="main_slider_wrap">
    <div class="container full-desktop-height">
        <div class="row form-horizontal">
            <div class="form-group col-xs-12 col-xxs-12">
                <div class="col-sm-12 text-center">Изменить Пароль</div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <label for="input-pass" class="col-sm-6 control-label">Пароль</label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" id="input-pass" placeholder="Пароль" value="">
                </div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <label for="input-pass2" class="col-sm-6 control-label">Повторите пароль</label>
                <div class="col-sm-4">
                    <input type="password" class="form-control" id="input-pass2" placeholder="Повторите пароль" value="">
                </div>
            </div>
            <div class="form-group col-xs-12 col-xxs-12">
                <div class="col-sm-offset-5 col-sm-9">
                    <button id="save-settings-data" type="button" class="btn btn-orange">Сохранить</button>
                </div>
            </div>
        </div>
    </div>
</div>

