<nav class="navbar navbar-default no-margin">
    <div class="container">
        <!-- mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- desktop display -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav" id="main-line-menu">
                <?php if (isset($this->userData->roleId) && $this->userData->roleId == User::ROLE_ADMIN) : ?>
                    <li>Admin</li>
                <?php endif; ?>
                <li <?= ($this->currentUrl == 'user') ? 'class="active"' : ""; ?>>
                    <a class="personal-a" href="/user" >Личные Данные</a>
                </li>
                <li <?= ($this->currentUrl == 'user/adverts') ? 'class="active"' : ""; ?>>
                    <a class="personal-a" href="/user/adverts">Обьявления</a>
                </li>
                <li <?= ($this->currentUrl == 'user/messages') ? 'class="active"' : ""; ?>>
                    <a class="personal-a" href="/user/messages">Сообщения</a>
                </li>
                <li <?= ($this->currentUrl == 'user/settings') ? 'class="active"' : ""; ?>>
                    <a class="personal-a" href="/user/settings">Настройки</a>
                </li>
                <li><a class="personal-a logout-user" href="javascript:void(0);">Выход</a></li>
            </ul>

        </div>
    </div>
</nav>


