<nav class="navbar navbar-default">
    <div class="container">
        <!-- mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- desktop display -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/user">Личные Данные</a></li>
                <li><a href="/user/adverts">Обьявления</a></li>
                <li><a href="/user/messages">Сообщения</a></li>
                <li><a href="/user/settings">Настройки</a></li>
                <li><a class="logout-user" href="javascript:void(0);">Выход</a></li>
            </ul>

        </div>
    </div>
</nav>