DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `role_id` tinyint(2) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `date` int(11) NOT NULL,
  `contact_email` varchar(255) DEFAULT NULL,
  `contact_phone` varchar(255) DEFAULT NULL,
  `contact_profile_1` varchar(255) DEFAULT NULL,
  `contact_profile_2` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `email_2` (`email`)
);
INSERT INTO `users` (`id`, `name`, `role_id`, `password`, `email`, `date`, `contact_email`, `contact_phone`, `contact_profile_1`, `contact_profile_2`) VALUES
('', 'Padavan', 10, '$3M16C4djjygQ', 'padavanzp1@gmail.com', 1472070707, 'rtyrty@qwe.we5', '53453453', 'https://vk.com/id=2', 'https://www.drive2.ru/r/opel/857268/'),
('', 'Barakuda', 10, '$3M16C4djjygQ', 'barakudatm@gmail.com', 1472070707, 'rtyrty@qwe.we5', '53453453', 'https://vk.com/id=1', 'https://www.drive2.ru/r/volvo/1327899/');


DROP TABLE IF EXISTS models;
CREATE TABLE models (
`id` INT (11) AUTO_INCREMENT,
`title` VARCHAR(60) NOT NULL,
`manufacture_id` INT(4) NOT NULL,
`type` ENUM('CAR','WHEEL','TYRES','SPACERS'),
`year_start` YEAR NULL,
`year_end` YEAR NULL,
PRIMARY KEY (id)
) COMMENT = 'таблица моделей изделий';

INSERT INTO models () VALUES('','RS',3,'WHEEL','',''),('','A',4,'WHEEL','',''),('','e30',1,'CAR','',''),('','100 Avant',2,'CAR','','');

DROP TABLE IF EXISTS wheels;
CREATE TABLE wheels (
`id` INT (10) AUTO_INCREMENT,
`nn` INT(1) NOT NULL COMMENT 'количество посадочных отверстий',
`pcd` INT(3) NOT NULL COMMENT 'диаметр посадочных отверстий мм',
`et` INT(3) NOT NULL COMMENT 'вылет мм',
`co_dia` INT(3) NOT NULL COMMENT 'диаметр центрального отверстия мм',
`ww` FLOAT NOT NULL COMMENT 'ширина диска дюйм',
`w_dia` INT(3) NOT NULL COMMENT 'диаметр диска',
PRIMARY KEY (id)
) COMMENT = 'таблица диски';

INSERT INTO wheels () VALUES('',4,100,35,40,6.7,17);

DROP TABLE IF EXISTS tires;
CREATE TABLE tires (
`id` INT (10) AUTO_INCREMENT,
`wt` INT(3) COMMENT 'ширина шины в мм',
`ph` INT(3) COMMENT 'высота профиля в процентах',
`t_dia` INT(3) COMMENT 'диаметр шины',
PRIMARY KEY (id)
) COMMENT = 'таблица шины';

DROP TABLE IF EXISTS spacers;
CREATE TABLE spacers (
`id` INT(11) AUTO_INCREMENT,
`nn` INT(1) NOT NULL COMMENT 'количество посадочных отверстий',
`pcd` INT(3) NOT NULL COMMENT 'диаметр посадочных отверстий мм',
`width` INT(3) NULL COMMENT 'ширина мм',
PRIMARY KEY (id)
) COMMENT = 'таблица проставки';

DROP TABLE IF EXISTS advert;
CREATE TABLE advert (
`id` INT (11) AUTO_INCREMENT,
`title` VARCHAR(70) NOT NULL COMMENT 'название',
`description` VARCHAR(4096) NOT NULL COMMENT 'описание',
`model_id` INT(11) NULL,
`manufacture_id` INT(11) NULL,
`wheel_id` INT(11) NULL,
`tires_id` INT(11) NULL,
`spacers_id` INT(11) NULL,
`user_id` INT(11) NOT NULL,
`price` INT(11) DEFAULT 0 NOT NULL,
PRIMARY KEY (id)
) COMMENT = 'таблица объявлений';
INSERT INTO advert (`title`,`description`,`model_id`,`manufacture_id`,`user_id`,`price`) VALUES
('Продам диски крутые r15','купи самые крутые диски, ёпта, тебе что впадлу,ска??',10,20,1,400),
('В продаже отличные проставки','Простаки переходные с 4х100 в 4х108',51,42,2,9000),
('проставки 5х120 10mm','проставки',110,29,2,6700),
('диски на опель астра','оригинал, штампы',71,23,1,7899);



DROP TABLE IF EXISTS vehicle_association;
CREATE TABLE vehicle_association (
`id` INT(11) AUTO_INCREMENT,
`model_id` INT(11) NOT NULL,
`wheel_id` INT(11) NOT NULL,
`tires_id` INT(11) NOT NULL,
PRIMARY KEY (id)
) COMMENT = '';
INSERT INTO vehicle_association () VALUES('',3,1,2);


DROP TABLE IF EXISTS countrys;
CREATE TABLE `countrys` (
`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`title_ru` VARCHAR(32) UNIQUE NOT NULL
);
INSERT INTO `countrys` (`title_ru`) VALUES
('ИТАЛИЯ'),
('АНГЛИЯ'),
('ГЕРМАНИЯ'),
('РОССИЯ/СССР'),
('США'),
('КИТАЙ'),
('ФРАНЦИЯ'),
('РУМЫНИЯ'),
('КОРЕЯ'),
('ЯПОНИЯ'),
('АВСТРАЛИЯ'),
('ШВЕЦИЯ'),
('ИНДИЯ'),
('МАЛАЙЗИЯ'),
('ИРАН'),
('ИСПАНИЯ'),
('ЧЕХИЯ'),
('НИДЕРЛАДНЫ'),
('АРГЕНТИНА');

DROP TABLE IF EXISTS manufacture;
CREATE TABLE `manufacture` (
`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`img_position` INT(4) NOT NULL,
`type` VARCHAR(30)  DEFAULT 'car' NOT NULL,
`title` VARCHAR(32) NOT NULL,
`counrty_id` INT(6) UNSIGNED NOT NULL,
`hide` BOOLEAN DEFAULT FALSE NOT NULL,
UNIQUE KEY (`type`, `title`)
);
INSERT INTO `manufacture` (`img_position`,`title`,`counrty_id`) VALUES
(0,'ALFA_ROMEO',1),
(1,'ASTON_MARTIN',2),
(2,'AUDI',3),
(3,'AZLK',4),
(4,'BENTLEY',2),
(5,'BMW',3),
(6,'BUGATTI',2),
(7,'BUICK',5),
(8,'CADILLAC',5),
(9,'CATERHAM',2),
(10,'CHERY',6),
(11,'CHEVROLET',5),
(12,'CHRYSLER',5),
(13,'CITROEN',7),
(14,'DACIA',8),
(15,'DAEWOO',9),
(16,'DAIHATSU',10),
(17,'DAIMLER',3),
(18,'DE_TOMASO',1),
(19,'DE_LOREAN',5),
(20,'DODGE',5),
(21,'FAW',6),
(22,'FERRARI',1),
(23,'FIAT',1),
(24,'FORD',5),
(25,'GAZ',4),
(26,'GEELY',6),
(27,'GENERAL_MOTORS',5),
(28,'GMC',5),
(29,'GREAT_WALL',6),
(30,'HOLDEN',11),
(31,'HONDA',10),
(32,'HUMMER',5),
(33,'HYUNDAI',9),
(34,'INFINITI',10),
(35,'ISUZU',10),
(36,'IVECO',1),
(37,'IZH',4),
(38,'JAGUAR',2),
(39,'JEEP',5),
(40,'KAMAZ',4),
(41,'KAWZ',4),
(42,'KIA',9),
(43,'KOENIGSEGG',12),
(44,'KRAZ',4),
(45,'LADA',4),
(46,'LAMBORGHINI',1),
(47,'LANCIA',1),
(48,'LAND_ROVER',2),
(49,'LAZ',4),
(50,'LEXUS',10),
(51,'LIAZ',4),
(52,'LIGIER',7),
(53,'LINCOLN',5),
(54,'LOTUS',2),
(55,'LUAZ',4),
(56,'DEUTZ',3),
(57,'MAHINDRA',13),
(58,'MAN',3),
(59,'MARCOS',2),
(60,'MARUSSIA',4),
(61,'MASERATI',1),
(62,'MAYBACH',3),
(63,'MAZ',4),
(64,'MAZDA',10),
(65,'MCLAREN',2),
(66,'MERCEDES_BENZ',3),
(67,'MERCURY',5),
(68,'MG',2),
(69,'MINI',2),
(70,'MITSUBISHI',10),
(71,'MORGAN',2),
(72,'NISSAN',10),
(73,'NOBLE',2),
(74,'OLDSMOBILE',5),
(75,'OPEL',3),
(76,'PACKARD',5),
(77,'PAGANI',1),
(78,'PETERBILT',5),
(79,'PEUGEOT',7),
(80,'PLYMOUTH',5),
(81,'PONTIAC',5),
(82,'PORSCHE',3),
(83,'PROTON',14),
(84,'RAF',4),
(85,'RENAULT',7),
(86,'ROLLS_ROYCE',2),
(87,'ROVER',2),
(88,'SAAB',12),
(89,'IRAN_KHODRO',15),
(90,'SATURN',5),
(91,'?',0),
(92,'SCANIA',12),
(93,'SCION',5),
(94,'SEAT',16),
(95,'??',0),
(96,'SKODA',17),
(97,'SMART',3),
(98,'SPYKER',18),
(99,'SSANGYONG',9),
(100,'SUBARU',10),
(101,'SUZUKI',10),
(102,'TAGAZ',4),
(103,'TALBOT',2),
(104,'TATA',13),
(105,'TATRA',17),
(106,'TESLA',5),
(107,'TONGGONG',0),
(108,'TOYOTA',10),
(109,'TRABANT',3),
(110,'TRIUMPH',2),
(111,'TVR',2),
(112,'UAZ',4),
(113,'YRAL',4),
(114,'VAUXHALL',2),
(115,'VESPA',0),
(116,'VOLKSWAGEN',3),
(117,'VOLVO',12),
(118,'VOLJANIN',4),
(119,'WARTBURG',3),
(120,'WIESMANN',3),
(121,'AUTODIESEL',0),
(122,'ZANELLA',19),
(123,'ZAZ',4),
(124,'ZIL',4);
INSERT INTO `manufacture` (`img_position`, `title`, `type`) VALUES
('4','AGATE','tire'),
('0','ACCELERA','tire'),
('1','ACHILLES','tire'),
('2','ADVANCE','tire'),
('3','AEOLUS','tire'),
('6','AMBERSTONE','tire'),
('7','AMTEL','tire'),
('8','ANNAITE','tire'),
('9','ANTYRE','tire'),
('5','ALTENZO','tire'),
('10','AONAITE','tire'),
('11','APOLLO','tire'),
('12','ARMOUR','tire'),
('14','ATHOS','tire'),
('13','ASHK','tire'),
('15','ATTURO','tire'),
('16','AUFINE','tire'),
('17','AURORA','tire'),
('18','AUSTONE','tire'),
('19','AVON','tire'),
('20','BARKLEY','tire'),
('21','BARUM','tire'),
('22','BCT','tire'),
('23','BELSHINA','tire'),
('24','BENTON','tire'),
('25','BESTRICH','tire'),
('26','BFGOODRICH','tire'),
('27','BLACKSTONE','tire'),
('28','BONTYRE','tire'),
('29','BOTO','tire'),
('30','BRIDGESTONE','tire'),
('31','CARLISLE','tire'),
('32','CEAT','tire'),
('33','CHANGFENG','tire'),
('35','CONTINENTAL','tire'),
('36','CONTYRE','tire'),
('37','COOPER','tire'),
('38','CORDIANT','tire'),
('34','CONSTANCY','tire'),
('39','CULTOR','tire'),
('40','DAEWOO','tire'),
('41','DAYTON','tire'),
('42','DEAN','tire'),
('43','DEBICA','tire'),
('44','DEESTONE','tire'),
('45','DIPLOMAT','tire'),
('48','DOUBLE_COIN','tire'),
('49','DOUBLESTAR','tire'),
('50','DUNLOP','tire'),
('47','DNEPROSHINA','tire'),
('51','DURUN','tire'),
('52','EVERGREEN','tire'),
('53','FALKEN','tire'),
('54','FEDERAL','tire'),
('55','FENIX','tire'),
('46','DMACK','tire'),
('57','FIRESTONE','tire'),
('58','FIRSTSTOP','tire'),
('59','FORCE','tire'),
('56','FESITE','tire'),
('60','FORMULA_(PIRELLI)','tire'),
('61','FORTUNA','tire'),
('62','FULDA','tire'),
('63','FULL_BORE','tire'),
('64','FULLRUN','tire'),
('65','FULLWAY','tire'),
('66','FUZION','tire'),
('67','GENERAL_TIRE','tire'),
('68','GISLAVED','tire'),
('70','GOLDSHIELD','tire'),
('71','GOODRIDE','tire'),
('69','GOFORM','tire'),
('72','GOODTYRE','tire'),
('73','GOODWAY','tire'),
('74','GOODYEAR','tire'),
('75','GREMAX','tire'),
('76','GRIPMAX','tire'),
('77','GT_RADIAL','tire'),
('78','HAIDA','tire'),
('79','HANKOOK','tire'),
('80','HEADWAY','tire'),
('81','HEMISPHERE','tire'),
('82','HERCULES','tire'),
('84','HORIZON','tire'),
('85','INFINITY','tire'),
('86','INSA_TURBO','tire'),
('87','INTERSTATE','tire'),
('83','HIFLY','tire'),
('88','ITP','tire'),
('89','JINYU','tire'),
('90','KAMA','tire'),
('91','KELLY','tire'),
('92','KENDA','tire'),
('93','KINGSTAR','tire'),
('94','KLEBER','tire'),
('95','KORMORAN','tire'),
('96','KSHZ','tire'),
('97','KUMHO','tire'),
('98','LANDER_SEA','tire'),
('99','LANDSAIL','tire'),
('101','LASSA','tire'),
('102','LINGLONG','tire'),
('103','LONG_MARCH','tire'),
('104','MABOR','tire'),
('100','LANVIGATOR','tire'),
('105','MALHOTRA','tire'),
('106','MALOYA','tire'),
('107','MANSORY','tire'),
('108','MARANGONI','tire'),
('109','MARSHAL','tire'),
('110','MASTER','tire'),
('112','MATADOR','tire'),
('111','MASTERCRAFT','tire'),
('113','MAXTREK','tire'),
('114','MAXXIS','tire'),
('115','MEDALIST','tire'),
('116','MENTOR','tire'),
('117','MERIT','tire'),
('118','METZELER','tire'),
('119','MICHELIN','tire'),
('120','MINERVA','tire'),
('121','MIRAGE','tire'),
('122','MITAS','tire'),
('123','MOTRIO','tire'),
('124','NANKANG','tire'),
('125','NEXEN','tire'),
('126','NITTO','tire'),
('127','NOKIAN','tire'),
('128','ODYKING','tire'),
('129','OGREEN','tire'),
('130','OHTSU','tire'),
('131','OMSKSHINA','tire'),
('132','OTANI','tire'),
('133','OVATION','tire'),
('134','PAXARO','tire'),
('135','PETLAS','tire'),
('136','PIRELLI','tire'),
('137','POINTS','tire'),
('138','POWERTRAC','tire'),
('139','PREMIORRI','tire'),
('140','PRESA','tire'),
('141','PROFIL','tire'),
('142','RADAR','tire'),
('143','RIKEN','tire'),
('144','ROADLUX','tire'),
('146','ROADSTONE','tire'),
('147','ROADWING','tire'),
('148','ROCKSTONE','tire'),
('149','ROSAVA','tire'),
('150','ROTALLA','tire'),
('151','RUIFULAI','tire'),
('152','SAILUN','tire'),
('154','SAVA','tire'),
('155','SEBRING','tire'),
('153','SATOYA','tire'),
('156','SEMPERIT','tire'),
('157','SILVERSTONE','tire'),
('158','SINORIENT','tire'),
('159','SONNY','tire'),
('161','SPORTRAK','tire'),
('162','STAR_PERFORMER','tire'),
('163','STARFIRE','tire'),
('164','STARMAXX','tire'),
('165','STRIAL','tire'),
('166','SUMITOMO','tire'),
('167','SUMO','tire'),
('168','SUNFULL','tire'),
('169','SUNITRAC','tire'),
('170','SUNNY','tire'),
('171','SUNTEK','tire'),
('173','TAITONG','tire'),
('174','TAURUS','tire'),
('172','SYRON','tire'),
('175','THREE-A','tire'),
('145','ROADSHINE','tire'),
('176','TIGAR','tire'),
('177','TOMASON','tire'),
('178','TORQUE','tire'),
('179','TOYO','tire'),
('180','TRACMAX','tire'),
('181','TRANSTONE','tire'),
('182','TRAYAL','tire'),
('183','TRELLEBORG','tire'),
('184','TRIANGLE','tire'),
('185','TRISTAR','tire'),
('186','TUNGA','tire'),
('187','TYREX','tire'),
('188','UNIROYAL','tire'),
('189','UNITREAD','tire'),
('190','VALSA','tire'),
('191','VIATTI','tire'),
('192','VIKING','tire'),
('193','VOLTYRE','tire'),
('194','VOYAGER','tire'),
('195','VREDESTEIN','tire'),
('196','WANLI','tire'),
('197','WARRIOR','tire'),
('198','WAYNNER','tire'),
('199','WESTLAKE','tire'),
('200','YASHZ','tire'),
('201','YELLOW_SEA','tire'),
('202','YOKOHAMA','tire'),
('203','ZEETEX','tire'),
('204','ZETA','tire'),
('205','ZETUM','tire'),
('160','SPORTIVA','tire'),
('0','4X4PROSPORT','wheel'),
('2','ADVANTI','wheel'),
('4','ALBA','wheel'),
('3','AEZ','wheel'),
('1','ADV.1','wheel'),
('5','ALCASTA','wheel'),
('6','ALUTEC','wheel'),
('8','ANTERA','wheel'),
('7','AMERICAN_RACING','wheel'),
('9','ASANTI','wheel'),
('10','ATP','wheel'),
('11','ATS','wheel'),
('12','AVANT_GARDE','wheel'),
('13','AVUS','wheel'),
('14','BALLISTIC','wheel'),
('15','BBS','wheel'),
('17','BLACK_RHINO','wheel'),
('16','BEYERN','wheel'),
('18','BORBET','wheel'),
('19','CEC','wheel'),
('20','COVENTRY','wheel'),
('21','DALE_EARNHARDT','wheel'),
('22','DEVINO','wheel'),
('23','DEZENT','wheel'),
('24','DIAMO','wheel'),
('25','DLW','wheel'),
('26','DOTZ','wheel'),
('27','DUB','wheel'),
('29','ENZO','wheel'),
('28','ENKEI','wheel'),
('30','ETA_BETA','wheel'),
('31','EUROSPORT','wheel'),
('33','FOOSE','wheel'),
('32','FONDMETAL','wheel'),
('34','FORGE-TEC','wheel'),
('35','FORGIATO','wheel'),
('36','FR_DESIGN','wheel'),
('37','FUEL_OFF-ROAD','wheel'),
('39','GIOVANNA_WHEELS','wheel'),
('38','GIANELLE_DESIGNS','wheel'),
('41','HELO','wheel'),
('42','HRE','wheel'),
('43','IFREE','wheel'),
('45','KELLENERS','wheel'),
('44','INCURVE_WHEELS','wheel'),
('46','KFZ','wheel'),
('47','KMC','wheel'),
('48','KOKO_KUTURE','wheel'),
('49','KONIG','wheel'),
('51','LF_WORKS','wheel'),
('50','LEXANI','wheel'),
('52','LORENZO','wheel'),
('53','LUMARAI','wheel'),
('54','M&K_FORGED_WHEELS','wheel'),
('55','MAK','wheel'),
('56','MAMBA','wheel'),
('57','MANDRUS','wheel'),
('58','MEGAMI','wheel'),
('59','MHT','wheel'),
('61','MODULAR_SOCIETY','wheel'),
('60','MILLE_MIGLIA','wheel'),
('62','MOTEGI_RACING','wheel'),
('63','MOTO_METAL','wheel'),
('64','MSW','wheel'),
('65','NICHE','wheel'),
('67','NZ','wheel'),
('66','NITRO','wheel'),
('68','OXIGIN','wheel'),
('70','PANTHER','wheel'),
('69','OZ_RACING','wheel'),
('73','REDBOURNE','wheel'),
('71','PDW','wheel'),
('72','PROMA','wheel'),
('74','RIAL','wheel'),
('75','RUSSTEC','wheel'),
('76','SPARCO','wheel'),
('77','STANCE_WHEELS','wheel'),
('78','STRUT','wheel'),
('79','TECH_LINE','wheel'),
('80','TEZZEN','wheel'),
('81','TIS','wheel'),
('82','TSW','wheel'),
('83','VERTINI_WHEELS','wheel'),
('84','VICTOR_EQUIPMENT','wheel'),
('85','VISSOL','wheel'),
('86','XD_SERIES','wheel'),
('87','Y.S.T.','wheel'),
('88','YOKATTA','wheel'),
('89','КИК_(K&K)','wheel'),
('90','СКАД','wheel'),
('91','REPLICA_CONCEPT','wheel'),
('92','REPLICA_FR','wheel'),
('93','REPLICA_H','wheel'),
('95','REPLICA_WSP','wheel'),
('96','REPLICA_YST','wheel'),
('94','REPLICA_LS','wheel');

SELECT models.id, manufacture.type AS `type`, manufacture.title AS `manufacture`,models.title AS `model`, `countrys`.`title_ru` AS `country` FROM models
LEFT JOIN (manufacture, countrys) ON ( models.manufacture_id = manufacture.id
AND manufacture.counrty_id = countrys.id);