DROP TABLE `countrys`;
DROP TABLE `manufacture`;

CREATE TABLE `manufacture` (
`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`img_position` INT(4) NOT NULL,
`type` VARCHAR(30)  DEFAULT 'car' NOT NULL,
`title` VARCHAR(32) UNIQUE NOT NULL,
`counrty_id` INT(6) UNSIGNED NOT NULL
);

INSERT INTO `manufacture` (`title`,`counrty_id`) VALUES
('ALFA_ROMEO',1),
('ASTON_MARTIN',2),
('AUDI',3),
('AZLK',4),
('BENTLEY',2),
('BMW',3),
('BUGATTI',2),
('BUICK',5),
('CADILLAC',5),
('CATERHAM',2),
('CHERY',6),
('CHEVROLET',5),
('CHRYSLER',5),
('CITROEN',7),
('DACIA',8),
('DAEWOO',9),
('DAIHATSU',10),
('DAIMLER',3),
('DE_TOMASO',1),
('DE_LOREAN',5),
('DODGE',5),
('FAW',6),
('FERRARI',1),
('FIAT',1),
('FORD',5),
('GAZ',4),
('GEELY',6),
('GENERAL_MOTORS',5),
('GMC',5),
('GREAT_WALL',6),
('HOLDEN',11),
('HONDA',10),
('HUMMER',5),
('HYUNDAI',9),
('INFINITI',10),
('ISUZU',10),
('IVECO',1),
('IZH',4),
('JAGUAR',2),
('JEEP',5),
('KAMAZ',4),
('KAWZ',4),
('KIA',9),
('KOENIGSEGG',12),
('KRAZ',4),
('LADA',4),
('LAMBORGHINI',1),
('LANCIA',1),
('LAND_ROVER',2),
('LAZ',4),
('LEXUS',10),
('LIAZ',4),
('LIGIER',7),
('LINCOLN',5),
('LOTUS',2),
('LUAZ',4),
('DEUTZ',3),
('MAHINDRA',13),
('MAN',3),
('MARCOS',2),
('MARUSSIA',4),
('MASERATI',1),
('MAYBACH',3),
('MAZ',4),
('MAZDA',10),
('MCLAREN',2),
('MERCEDES_BENZ',3),
('MERCURY',5),
('MG',2),
('MINI',2),
('MITSUBISHI',10),
('MORGAN',2),
('NISSAN',10),
('MOBLE',2),
('OLDSMOBILE',5),
('OPEL',3),
('PACKARD',5),
('PAGANI',1),
('PETERBILT',5),
('PEUGEOT',7),
('PLYMOUTH',5),
('PONTIAC',5),
('PORSCHE',3),
('PROTON',14),
('RAF',4),
('RENAULT',7),
('ROLLS_ROYCE',2),
('ROVER',2),
('SAAB',12),
('IRAN_KHODRO',15),
('SATURN',5),
('?',0),
('SCANIA',12),
('SCION',5),
('SEAT',16),
('??',0),
('SKODA',17),
('SMART',3),
('SPYKER',18),
('SSANGYONG',9),
('SUBARU',10),
('SUZUKI',10),
('TAGAZ',4),
('TALBOT',2),
('TATA',13),
('TATRA',17),
('TESLA',5),
('TONGGONG',0),
('TOYOTA',10),
('TRABANT',3),
('TRIUMPH',2),
('TVR',2),
('UAZ',4),
('YRAL',4),
('VAUXHALL',2),
('VESPA',0),
('VOLKSWAGEN',3),
('VOLVO',12),
('VOLJANIN',4),
('WARTBURG',3),
('WIESMANN',3),
('AUTODIESEL',0),
('ZANELLA',19),
('ZAZ',4),
('ZIL',4);

UPDATE `manufacture` SET `img_position`= `id`;

DROP TABLE `countrys`;

CREATE TABLE `countrys` (
`id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`title_ru` VARCHAR(32) UNIQUE NOT NULL
);

INSERT INTO `countrys` (`title_ru`) VALUES
('ИТАЛИЯ'),
('АНГЛИЯ'),
('ГЕРМАНИЯ'),
('РОССИЯ/СССР'),
('США'),
('КИТАЙ'),
('ФРАНЦИЯ'),
('РУМЫНИЯ'),
('КОРЕЯ'),
('ЯПОНИЯ'),
('АВСТРАЛИЯ'),
('ШВЕЦИЯ'),
('ИНДИЯ'),
('МАЛАЙЗИЯ'),
('ИРАН'),
('ИСПАНИЯ'),
('ЧЕХИЯ'),
('НИДЕРЛАДНЫ'),
('АРГЕНТИНА');